# 서버 포트 번호
server:
  port: 8086
  servlet:
    encoding:
      charset: UTF-8

# mysql, jpa 관련
spring:
  application:
    name: team
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:log4jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        # JPA 변수 명명규칙을 카멜 케이스로 설정
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    user:
      name: ${SECURITY_ID}
      password: ${SECURITY_PW}

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/**/*.xml
  type-aliases-package: sansam.team.**

cloud:
  aws:
    s3:
      bucket: sansamforce
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

# logging setting
logging:
  file:
    path: C:/logs/team
  level:
    root: info
    org.springframework.web: info
    com.zaxxer.hikari: info
    log4jdbc.log4j2: error
    jdbc.sqlonly: info
    jdbc.resultsettable: info
    jdbc.connection: info

springdoc:
  swagger-ui:
    path: /
# swagger-ui ?? ??? ?? ??, ?? ??? ???? http://localhost:8080/swagger-ui/index.html? ????? ?.
#    #path, query, body, response ??? ??
#    groups-order: DESC
#    #??? ??? ??? ??
#    tags-sorter: alpha
#    #delete - get - patch - post - put ??? ??, alpha? ???? ??? ??? ?? ??
#    operations-sorter: method
#   # swagger-ui? ??? api? ????? ??
#  paths-to-match:
#    - /api/**