services:
  mysql:
    image: mysql:latest
    container_name: mysqldb_sansam
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - springboot-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_sansam
    restart: always
    environment:
      PMA_HOST: mysqldb_sansam
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8090:80"
    networks:
      - springboot-network

  mongodb:
    image: mongo:latest
    container_name: mongodb_sansam
    restart: always
    env_file:
      - .env
    volumes:
      - mongodb-data:/data/db
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express
    container_name: mongo-express_sansam
    restart: always
    ports:
      - '8091:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on:
      - mongodb

#  spring:
#    build:
#      context: ./toyProject
#      dockerfile: DockerFile
#    depends_on:
#      - mysql
#    ports:
#      - "8084:8084"

volumes:
  db_data:
  mongodb-data:

networks:
  springboot-network:
    driver: bridge